- src/lib/components/OrdersList.svelte
- src/lib/types/Order.ts
- src/routes/(app)/admin[[hash=admin_hash]]/order/+page.server.ts
Implement pagination on /admin/order #1155
> Implement pagination on /admin/order #1155

- src/lib/components/OrdersList.svelte
- src/lib/types/Order.ts
- src/routes/(app)/admin[[hash=admin_hash]]/order/+page.server.ts
- src/routes/(app)/admin[[hash=admin_hash]]/order/+page.svelte
🦋 Add search order by number on /admin/order #1156
> Search order by number

- src/routes/(app)/order/[id]/payment/[paymentId]/receipt/+page.svelte
> 🩹 Add country in invoice address

- src/lib/translations/en.json
- src/lib/translations/fr.json
- src/routes/(app)/pos/+page.svelte
🦋 On /pos, add a link to admin page in new tab #1180
> On /pos, add a link to admin page in new tab #1180

- src/routes/(app)/admin[[hash=admin_hash]]/reporting/+page.server.ts
- src/routes/(app)/admin[[hash=admin_hash]]/reporting/+page.svelte
🦋 Add custom invoice number in /admin/reporting on Payment Detail #1189
> Add custom invoice number in /admin/reporting on Payment Detail #1189

- src/lib/server/runtime-config.ts
- src/routes/(app)/+layout.server.ts
- src/routes/(app)/+layout.svelte
- src/routes/(app)/admin[[hash=admin_hash]]/config/+page.server.ts
- src/routes/(app)/admin[[hash=admin_hash]]/config/+page.svelte
🦋 Remove fr/en selector on a admin parameter #1198
> Remove fr/en selector on a admin parameter #1198

- src/lib/components/CmsForm.svelte
- src/lib/components/CmsPage.svelte
- src/lib/types/CmsPage.ts
- src/routes/(app)/[slug]/+page.server.ts
- src/routes/(app)/admin[[hash=admin_hash]]/cms/[slug]/+page.server.ts
🐱‍👤Add an option to hide CMS Page from SEO crawlers #1201
> Add an option to hide CMS Page from SEO crawlers #1201

- src/routes/(app)/checkout/+page.svelte
replace this PR https://github.com/B2Bitcoin/beBOP/pull/1182
> Allow 100% discount on an order on POS seat #1179

- src/routes/(app)/admin[[hash=admin_hash]]/product/[id]/+page.server.ts
🦋 Change preorder product date information on /admin/product/{id} #1222
> Change preorder product date information on /admin/product/{id} #1222

- src/app.html
- src/lib/server/runtime-config.ts
- src/routes/(app)/+layout.server.ts
- src/routes/(app)/admin[[hash=admin_hash]]/layout/+page.server.ts
- src/routes/(app)/admin[[hash=admin_hash]]/layout/+page.svelte
- src/routes/+layout.server.ts
- src/routes/+layout.svelte
Add a "Mobile behavior" selector on /admin/layout #1237
> 📱 Add a 'Mobile behavior' selector on /admin/layout #1237

- src/routes/(app)/+layout.svelte
📱 Change header theme style management on mobile view #1249
> Change header theme style management on mobile view #1249

- src/lib/components/CmsDesign.svelte
- src/lib/components/CmsForm.svelte
- src/lib/components/CmsPage.svelte
- src/lib/server/cms.ts
- src/lib/types/CmsPage.ts
- src/routes/(app)/+page.server.ts
- src/routes/(app)/[slug]/+page.server.ts
- src/routes/(app)/[slug]/+page.svelte
- src/routes/(app)/[slug]/[sub]/[...catchall]/+page.server.ts
- src/routes/(app)/admin[[hash=admin_hash]]/cms/+page.server.ts
- src/routes/(app)/admin[[hash=admin_hash]]/cms/+page.svelte
- src/routes/(app)/admin[[hash=admin_hash]]/cms/[slug]/+page.server.ts
- src/routes/(app)/admin[[hash=admin_hash]]/cms/[slug]/cms-schema.ts
- src/routes/(app)/admin[[hash=admin_hash]]/cms/[slug]/translations/+page.svelte
- src/routes/(app)/admin[[hash=admin_hash]]/cms/new/+page.server.ts
- src/routes/(app)/cart/+page.server.ts
- src/routes/(app)/checkout/+page.server.ts
- src/routes/(app)/order/[id]/+page.server.ts
- src/routes/(app)/product/[id]/+layout.server.ts
- src/routes/(app)/product/[id]/+page.server.ts
📱 Allow Owner to substitute a CMS page to another for mobile display #1247
> Allow Owner to substitute a CMS page to another for mobile display #1247

- src/routes/(app)/+layout.svelte
- src/routes/(app)/checkout/+page.svelte
- src/routes/(app)/order/[id]/+page.svelte
- src/routes/(app)/product/[id]/+page.svelte
> Harmonize mobile page version

- src/lib/components/TagWidget.svelte
- src/lib/components/TagWidget/TagWidgetVariation1ReversenoUC.svelte
- src/lib/components/TagWidget/TagWidgetVariation1noUC.svelte
- src/routes/(app)/tag/[id]/+page.svelte
> Create Tag widget 1 template variation without title uppercase #1255

- src/routes/(app)/+layout.svelte
- src/routes/(app)/checkout/+page.svelte
- src/routes/(app)/order/[id]/+page.svelte
- src/routes/(app)/product/[id]/+page.svelte
Harmonize mobile page version vs mobile header version on dedicated width #1254
> Harmonize mobile page version vs mobile header version on dedicated width #1254

- src/lib/components/ProductWidget.svelte
- src/lib/components/ProductWidget/ProductWidgetMobile.svelte
- src/lib/components/ProductWidget/ProductWidgetVariation2.svelte
📱 Create a mobile-dedicated product widget variation #1240
> Create a mobile-dedicated product widget variation #1240

- src/lib/translations/en.json
- src/lib/translations/fr.json
- src/lib/types/Ticket.ts
- src/routes/(app)/admin[[hash=admin_hash]]/ticket/[ticketId]/burn/+page.server.ts
- src/routes/(app)/admin[[hash=admin_hash]]/ticket/[ticketId]/unburn/+page.server.ts
- src/routes/(app)/ticket/[id]/+page.server.ts
- src/routes/(app)/ticket/[id]/+page.svelte
Fix https://github.com/B2Bitcoin/beBOP/issues/1067
> ✨ Add burn/unburn of ticket

- src/routes/(app)/admin[[hash=admin_hash]]/tags/+page.svelte
- src/routes/(app)/admin[[hash=admin_hash]]/tags/new/+page.svelte
Request tag pos-favorite creation #1301
> Request tag pos-favorite creation #1301

- src/lib/components/CarouselWidget.svelte
Discord Issue
https://discord.com/channels/1022592041709998080/1088417396232028170/1260138572703469628
> fix slide block disappearing

- src/lib/translations/es-sv.json
- src/lib/translations/index.ts
Added new translation file.
I have not built the project, so I'm not sure the contents of this patch series are enough to make it available. Feel free to comment on the MR or push to the branch shall there be something missing.
> Add Spanish (El Salvador) translations

- src/lib/translations/index.ts
- src/lib/translations/nl.json
Fix https://github.com/B2Bitcoin/beBOP/issues/1404
> 🌐 Translate to dutch

- src/lib/components/OrderLabelComponent.svelte
- src/lib/components/OrdersList.svelte
- src/lib/server/database.ts
- src/lib/types/Order.ts
- src/lib/types/OrderLabel.ts
- src/routes/(app)/admin[[hash=admin_hash]]/adminLinks.ts
- src/routes/(app)/admin[[hash=admin_hash]]/label/+page.server.ts
- src/routes/(app)/admin[[hash=admin_hash]]/label/+page.svelte
- src/routes/(app)/admin[[hash=admin_hash]]/label/[id]/+layout.server.ts
- src/routes/(app)/admin[[hash=admin_hash]]/label/[id]/+layout.svelte
- src/routes/(app)/admin[[hash=admin_hash]]/label/[id]/+page.server.ts
- src/routes/(app)/admin[[hash=admin_hash]]/label/[id]/+page.svelte
- src/routes/(app)/admin[[hash=admin_hash]]/label/[id]/contact-form-schema.ts
- src/routes/(app)/admin[[hash=admin_hash]]/label/[id]/label-schema.ts
- src/routes/(app)/admin[[hash=admin_hash]]/label/[id]/translations/+page.server.ts
- src/routes/(app)/admin[[hash=admin_hash]]/label/[id]/translations/+page.svelte
- src/routes/(app)/admin[[hash=admin_hash]]/label/new/+page.server.ts
- src/routes/(app)/admin[[hash=admin_hash]]/label/new/+page.svelte
- src/routes/(app)/admin[[hash=admin_hash]]/order/+page.server.ts
- src/routes/(app)/admin[[hash=admin_hash]]/order/+page.svelte
- src/routes/(app)/admin[[hash=admin_hash]]/order/[id]/label/+page.server.ts
- src/routes/(app)/admin[[hash=admin_hash]]/order/[id]/label/+page.svelte
- src/routes/(app)/label/[id]/+page.server.ts
- src/routes/(app)/label/[id]/+page.svelte
>  Use, filter on and create order labels

- .github/workflows/lint.yml
- scripts/check-translations.mjs
- src/lib/translations/nl.json
Follow up https://github.com/B2Bitcoin/beBOP/pull/1410
Also add a script to do some automated checks
> 🌐 Fix dutch parameter names

- src/lib/server/locks/handle-messages.ts
- src/lib/server/runtime-config.ts
- src/routes/(app)/admin[[hash=admin_hash]]/nostr/+page.server.ts
- src/routes/(app)/admin[[hash=admin_hash]]/nostr/+page.svelte
🦩 Add an BO admin flag to disable Nostr-bot intro message #1424
> Add an BO admin flag to disable Nostr-bot intro message #1424

- src/lib/components/ProductForm.svelte
- src/lib/server/picture.ts
- src/lib/server/s3.ts
- src/lib/types/Picture.ts
- src/routes/(app)/admin[[hash=admin_hash]]/backup/create/+server.ts
- src/routes/(app)/admin[[hash=admin_hash]]/gallery/[id]/+page.server.ts
- src/routes/(app)/admin[[hash=admin_hash]]/gallery/[id]/+page.svelte
- src/routes/(app)/admin[[hash=admin_hash]]/gallery/new/+page.server.ts
- src/routes/(app)/admin[[hash=admin_hash]]/gallery/new/+page.svelte
- src/routes/(app)/admin[[hash=admin_hash]]/picture/new/+page.server.ts
- src/routes/(app)/admin[[hash=admin_hash]]/picture/new/+page.svelte
- src/routes/(app)/admin[[hash=admin_hash]]/product/new/+page.server.ts
- src/routes/(app)/admin[[hash=admin_hash]]/slider/new/+page.server.ts
- src/routes/(app)/admin[[hash=admin_hash]]/slider/new/+page.svelte
- src/routes/(app)/admin[[hash=admin_hash]]/tags/new/+page.server.ts
- src/routes/(app)/admin[[hash=admin_hash]]/tags/new/+page.svelte
- src/routes/(app)/picture/raw/[id]/format/[width]/+server.ts
cc @Tirodem 
Picture uploads have also been simplified cc @ithiame (feel free to check out the code) so would be nice to test picture upload again @Tirodem 
Should enable instant image loading on https://watchmakersunited.com/ and better SEO (if image was already loaded once)
> Image caching

- src/lib/server/runtime-config.ts
- src/routes/(app)/admin[[hash=admin_hash]]/adminLinks.ts
- src/routes/(app)/admin[[hash=admin_hash]]/seo/+page.server.ts
- src/routes/(app)/admin[[hash=admin_hash]]/seo/+page.svelte
- src/routes/+layout.server.ts
- src/routes/robots.txt/+server.ts
> Seo cloack

- src/lib/server/orders.ts
- src/lib/types/Challenge.ts
- src/routes/(app)/admin[[hash=admin_hash]]/challenge/[id]/+page.server.ts
- src/routes/(app)/admin[[hash=admin_hash]]/challenge/[id]/+page.svelte
🐛 🔬 Challenge gauge broken / flaky : add helpful tools https://github.com/B2Bitcoin/beBOP/issues/1496
> 🐛 list orders related to a challenge #1496

- src/lib/components/ProductForm.svelte
🦋 Raise error on product form if 2 variations have the same name + value #1515
> Raise error on product form if 2 variations have the same name + value

- src/routes/(app)/login/+page.svelte
🦋 Change npub session CTA behavior
[#1523](https://github.com/B2Bitcoin/beBOP/issues/1523)
> 🦋 Adapt npub display on mobile #1524

- src/lib/server/getConfirmationBlocks.test.ts
- src/lib/server/getConfirmationBlocks.ts
> 🐛 Fix confirmation blocks

- .env
- src/lib/server/locks/order-lock.ts
- src/lib/server/phoenixd.ts
> Alert admin on low inbound liquidity on phoenixd

- src/lib/server/database.ts
- src/routes/(app)/admin[[hash=admin_hash]]/reporting/+page.server.ts
- src/routes/(app)/admin[[hash=admin_hash]]/reporting/+page.svelte
Follow up to https://github.com/B2Bitcoin/beBOP/pull/1657
Before https://github.com/B2Bitcoin/beBOP/issues/1655
> Order reporting cleanup

- src/routes/(app)/admin[[hash=admin_hash]]/reporting/+page.svelte
- src/routes/(app)/order/[id]/payment/[paymentId]/receipt/+page.svelte
Fix https://github.com/B2Bitcoin/beBOP/issues/1655
I only tested with a few invoices
> ✨ Export everything as PDF

- src/lib/components/CmsForm.svelte
- src/lib/types/CmsPage.ts
>  Allow slug edition on creation but forbid uppercases, spaces and special characters in input
>     BTW, pages already created with uppercases and spaces previously to this PR should still work
> Improve cms page slug

- src/lib/components/ScheduleWidget/ScheduleWidgetCalendar.svelte
- src/routes/(app)/product/[id]/+page.svelte
https://discord.com/channels/1022592041709998080/1088417396232028170/1373936365649137694
> some css fix

- src/lib/components/SetLightningQrCodeDescription.svelte
- src/lib/server/actions.ts
- src/routes/(app)/admin[[hash=admin_hash]]/lnd/+page.server.ts
- src/routes/(app)/admin[[hash=admin_hash]]/lnd/+page.svelte
- src/routes/(app)/admin[[hash=admin_hash]]/phoenixd/+page.server.ts
- src/routes/(app)/admin[[hash=admin_hash]]/phoenixd/+page.svelte
- src/routes/(app)/admin[[hash=admin_hash]]/swiss-bitcoin-pay/+page.server.ts
- src/routes/(app)/admin[[hash=admin_hash]]/swiss-bitcoin-pay/+page.svelte
> Allow customizing LN invoice label on Phoenixd and SwissBitcoinPay

- src/lib/server/orders.ts
- src/routes/(app)/admin[[hash=admin_hash]]/discount/[id]/+page.server.ts
- src/routes/(app)/admin[[hash=admin_hash]]/discount/[id]/+page.svelte
Please see commit messages. Closes #1942
> 🦋 Enable admin to add missing discounts to existing subscriptions

- .github/workflows/lint.yml
This PR adds a check enforcing the branch is up-to-date with the target branch as part of the checks ran with the CI.
> CI: Check branch is up-to-date with target branch

- src/lib/components/ProductWidget/ProductWidgetPOS.svelte
- src/routes/(app)/admin[[hash=admin_hash]]/pos/+page.svelte
- src/routes/(app)/pos/touch/+layout.svelte
- src/routes/(app)/pos/touch/+page.server.ts
- src/routes/(app)/pos/touch/+page.svelte
- src/routes/(app)/pos/touch/touch.css
> Improve PoS Touchscreen interface

- src/lib/components/CmsDesign.svelte
- src/lib/components/CmsForm.svelte
- src/lib/components/CmsPage.svelte
- src/lib/server/cms.ts
- src/lib/types/CmsPage.ts
- src/routes/(app)/+layout.svelte
- src/routes/(app)/+page.server.ts
- src/routes/(app)/[slug]/+page.server.ts
- src/routes/(app)/admin[[hash=admin_hash]]/cms/[slug]/+page.server.ts
- src/routes/(app)/admin[[hash=admin_hash]]/cms/new/+page.server.ts
- src/routes/(app)/cart/+page.svelte
- src/routes/(app)/checkout/+page.svelte
- src/routes/(app)/order/[id]/+page.svelte
- src/routes/(app)/product/[id]/+page.svelte
Addresses https://github.com/be-BOP-io-SA/be-BOP/issues/2082.
> Enable advanced HTML edition on CMS pages
